server:
  port: 4040
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restoran
    password: altynbek695
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  jwt:
    secret_key: altynbek
#debug:
#  true
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){red} %clr(---){yellow} %clr([%15.15t]){grey} %clr(:){blue} %clr(%m){blue}%n"
